I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 98, in script
    define gui.main_menu_background = background
  File "game/gui.rpy", line 98, in script
    define gui.main_menu_background = background
  File "game/gui.rpy", line 98, in <module>
    define gui.main_menu_background = background
NameError: name 'background' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Soft\Renpy\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Soft\Renpy\renpy\main.py", line 526, in main
    renpy.game.context().run(node)
  File "game/gui.rpy", line 98, in script
    define gui.main_menu_background = background
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/gui.rpy", line 98, in script
    define gui.main_menu_background = background
  File "C:\Soft\Renpy\renpy\ast.py", line 2222, in execute
    self.set()
  File "C:\Soft\Renpy\renpy\ast.py", line 2236, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Soft\Renpy\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/gui.rpy", line 98, in <module>
    define gui.main_menu_background = background
NameError: name 'background' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
KarachunsDaughter 1.0
Fri Aug 23 00:23:25 2024
